const PREFIX = `@@shop`;

export const UPDATE_ACCOUNT_INFO = `${PREFIX}/UPDATE_ACCOUNT_INFO`;
export const UPDATE_ACCOUNT_INFO_START = `${PREFIX}/UPDATE_ACCOUNT_INFO_START`;
export const UPDATE_ACCOUNT_INFO_SUCCESS = `${PREFIX}/UPDATE_ACCOUNT_INFO_SUCCESS`;
export const UPDATE_ACCOUNT_INFO_ERROR = `${PREFIX}/UPDATE_ACCOUNT_INFO_ERROR`;
