const PREFIX = '@benefit';

export const FETCH_BENEFITS = `${PREFIX}/FETCH_BENEFITS`;
export const FETCH_BENEFITS_START = `${PREFIX}/FETCH_BENEFITS_START`;
export const FETCH_BENEFITS_SUCCESS = `${PREFIX}/FETCH_BENEFITS_SUCCESS`;
export const FETCH_BENEFITS_ERROR = `${PREFIX}/FETCH_BENEFITS_ERROR`;

export const FETCH_BENEFIT_DOCUMENTS = `${PREFIX}/FETCH_BENEFIT_DOCUMENTS`;
export const FETCH_BENEFIT_DOCUMENTS_START = `${PREFIX}/FETCH_BENEFIT_DOCUMENTS_START`;
export const FETCH_BENEFIT_DOCUMENTS_SUCCESS = `${PREFIX}/FETCH_BENEFIT_DOCUMENTS_SUCCESS`;
export const FETCH_BENEFIT_DOCUMENTS_ERROR = `${PREFIX}/FETCH_BENEFIT_DOCUMENTS_ERROR`;

export const FETCH_POLICY_DETAILS = `${PREFIX}/FETCH_POLICY_DETAILS`;
export const FETCH_POLICY_DETAILS_START = `${PREFIX}/FETCH_POLICY_DETAILS_START`;
export const FETCH_POLICY_DETAILS_SUCCESS = `${PREFIX}/FETCH_POLICY_DETAILS_SUCCESS`;
export const FETCH_POLICY_DETAILS_ERROR = `${PREFIX}/FETCH_POLICY_DETAILS_ERROR`;

export const FETCH_HEALTHCARDS = `${PREFIX}/FETCH_HEALTHCARDS`;
export const FETCH_HEALTHCARDS_START = `${PREFIX}/FETCH_HEALTHCARDS_START`;
export const FETCH_HEALTHCARDS_SUCCESS = `${PREFIX}/FETCH_HEALTHCARDS_SUCCESS`;
export const FETCH_HEALTHCARDS_ERROR = `${PREFIX}/FETCH_HEALTHCARDS_ERROR`;

export const FETCH_CXA1_BENEFITS_SIMPLIFIED = `${PREFIX}/FETCH_CXA1_BENEFITS_SIMPLIFIED`;
export const FETCH_CXA1_BENEFITS_SIMPLIFIED_START = `${PREFIX}/FETCH_CXA1_BENEFITS_SIMPLIFIED_START`;
export const FETCH_CXA1_BENEFITS_SIMPLIFIED_SUCCESS = `${PREFIX}/FETCH_CXA1_BENEFITS_SIMPLIFIED_SUCCESS`;
export const FETCH_CXA1_BENEFITS_SIMPLIFIED_ERROR = `${PREFIX}/FETCH_CXA1_BENEFITS_SIMPLIFIED_ERROR`;
