const PREFIX = '@@shop';

export const ADD_TO_CART = `${PREFIX}/ADD_TO_CART`;
export const ADD_TO_CART_START = `${PREFIX}/ADD_TO_CART_START`;
export const ADD_TO_CART_SUCCESS = `${PREFIX}/ADD_TO_CART_SUCCESS`;
export const ADD_TO_CART_ERROR = `${PREFIX}/ADD_TO_CART_ERROR`;

export const UPDATE_CART = `${PREFIX}/UPDATE_CART`;
export const UPDATE_CART_START = `${PREFIX}/UPDATE_CART_START`;
export const UPDATE_CART_SUCCESS = `${PREFIX}/UPDATE_CART_SUCCESS`;
export const UPDATE_CART_ERROR = `${PREFIX}/UPDATE_CART_ERROR`;

export const GET_CART = `${PREFIX}/GET_CART`;
export const GET_CART_START = `${PREFIX}/GET_CART_START`;
export const GET_CART_SUCCESS = `${PREFIX}/GET_CART_SUCCESS`;
export const GET_CART_ERROR = `${PREFIX}/GET_CART_ERROR`;

export const GET_CART_TOTALS = `${PREFIX}/GET_CART_TOTALS`;
export const GET_CART_TOTALS_START = `${PREFIX}/GET_CART_TOTALS_START`;
export const GET_CART_TOTALS_SUCCESS = `${PREFIX}/GET_CART_TOTALS_SUCCESS`;
export const GET_CART_TOTALS_ERROR = `${PREFIX}/GET_CART_TOTALS_ERROR`;

export const GET_CART_BILLING = `${PREFIX}/GET_CART_BILLING`;
export const GET_CART_BILLING_START = `${PREFIX}/GET_CART_BILLING_START`;
export const GET_CART_BILLING_SUCCESS = `${PREFIX}/GET_CART_BILLING_SUCCESS`;
export const GET_CART_BILLING_ERROR = `${PREFIX}/GET_CART_BILLING_ERROR`;

export const POST_CART_BILLING = `${PREFIX}/POST_CART_BILLING`;
export const POST_CART_BILLING_START = `${PREFIX}/POST_CART_BILLING_START`;
export const POST_CART_BILLING_SUCCESS = `${PREFIX}/POST_CART_BILLING_SUCCESS`;
export const POST_CART_BILLING_ERROR = `${PREFIX}/POST_CART_BILLING_ERROR`;

export const GET_CART_SHIPPING = `${PREFIX}/GET_CART_SHIPPING`;
export const GET_CART_SHIPPING_START = `${PREFIX}/GET_CART_SHIPPING_START`;
export const GET_CART_SHIPPING_SUCCESS = `${PREFIX}/GET_CART_SHIPPING_SUCCESS`;
export const GET_CART_SHIPPING_ERROR = `${PREFIX}/GET_CART_SHIPPING_ERROR`;

export const POST_CART_SHIPPING = `${PREFIX}/POST_CART_SHIPPING`;
export const POST_CART_SHIPPING_START = `${PREFIX}/POST_CART_SHIPPING_START`;
export const POST_CART_SHIPPING_SUCCESS = `${PREFIX}/POST_CART_SHIPPING_SUCCESS`;
export const POST_CART_SHIPPING_ERROR = `${PREFIX}/POST_CART_SHIPPING_ERROR`;

export const REMOVE_ITEM_FROM_CART = `${PREFIX}/REMOVE_ITEM_FROM_CART`;
export const REMOVE_ITEM_FROM_CART_START = `${PREFIX}/REMOVE_ITEM_FROM_CART_START`;
export const REMOVE_ITEM_FROM_CART_SUCCESS = `${PREFIX}/REMOVE_ITEM_FROM_CART_SUCCESS`;
export const REMOVE_ITEM_FROM_CART_ERROR = `${PREFIX}/REMOVE_ITEM_FROM_CART_ERROR`;

export const MAKE_PAYMENT = `${PREFIX}/MAKE_PAYMENT`;
export const MAKE_PAYMENT_START = `${PREFIX}/MAKE_PAYMENT_START`;
export const MAKE_PAYMENT_SUCCESS = `${PREFIX}/MAKE_PAYMENT_SUCCESS`;
export const MAKE_PAYMENT_ERROR = `${PREFIX}/MAKE_PAYMENT_ERROR`;

export const GET_SHIPPING_ADDRESS = `${PREFIX}/GET_SHIPPING_ADDRESS`;
export const GET_SHIPPING_ADDRESS_START = `${PREFIX}/GET_SHIPPING_ADDRESS_START`;
export const GET_SHIPPING_ADDRESS_SUCCESS = `${PREFIX}/GET_SHIPPING_ADDRESS_SUCCESS`;
export const GET_SHIPPING_ADDRESS_ERROR = `${PREFIX}/GET_SHIPPING_ADDRESS_ERROR`;

export const GET_BILLING_ADDRESS = `${PREFIX}/GET_BILLING_ADDRESS`;
export const GET_BILLING_ADDRESS_START = `${PREFIX}/GET_BILLING_ADDRESS_START`;
export const GET_BILLING_ADDRESS_SUCCESS = `${PREFIX}/GET_BILLING_ADDRESS_SUCCESS`;
export const GET_BILLING_ADDRESS_ERROR = `${PREFIX}/GET_BILLING_ADDRESS_ERROR`;

export const GET_CART_COUPONS = `${PREFIX}/GET_CART_COUPONS`;
export const GET_CART_COUPONS_START = `${PREFIX}/GET_CART_COUPONS_START`;
export const GET_CART_COUPONS_SUCCESS = `${PREFIX}/GET_CART_COUPONS_SUCCESS`;
export const GET_CART_COUPONS_ERROR = `${PREFIX}/GET_CART_COUPONS_ERROR`;

export const REMOVE_CART_COUPON = `${PREFIX}/REMOVE_CART_COUPON`;
export const REMOVE_CART_COUPON_START = `${PREFIX}/REMOVE_CART_COUPON_START`;
export const REMOVE_CART_COUPON_SUCCESS = `${PREFIX}/REMOVE_CART_COUPON_SUCCESS`;
export const REMOVE_CART_COUPON_ERROR = `${PREFIX}/REMOVE_CART_COUPON_ERROR`;

export const ADD_CART_COUPON = `${PREFIX}/ADD_CART_COUPON`;
export const ADD_CART_COUPON_START = `${PREFIX}/ADD_CART_COUPON_START`;
export const ADD_CART_COUPON_SUCCESS = `${PREFIX}/ADD_CART_COUPON_SUCCESS`;
export const ADD_CART_COUPON_ERROR = `${PREFIX}/ADD_CART_COUPON_ERROR`;
