const PREFIX = '@@shop';

export const SHOP_INITIALIZE = `${PREFIX}/SHOP_INITIALIZE`;
export const SHOP_INITIALIZE_START = `${PREFIX}/SHOP_INITIALIZE_START`;
export const SHOP_INITIALIZE_SUCCESS = `${PREFIX}/SHOP_INITIALIZE_SUCCESS`;
export const SHOP_INITIALIZE_ERROR = `${PREFIX}/SHOP_INITIALIZE_ERROR`;
